---

- name: template /etc/default/tomcat
  template:
    src: tomcat-defaults.j2
    dest: /etc/default/tomcat
  notify: restart tomcat
  when: ansible_os_family == 'Debian'

- name: template {{tomcat_home}}/bin/setenv.sh
  template:
    src: setenv.sh.j2
    dest: "{{tomcat_home}}/bin/setenv.sh"
  notify: restart tomcat
  when: ansible_os_family == 'RedHat'

- name: server configuration
  template:
    src: server.xml.j2
    dest: "{{tomcat_home}}/conf/server.xml"
  notify: restart tomcat
  become: yes

- name: template tomcat-users.xml
  template:
    src: tomcat-users.xml.j2
    dest: "{{tomcat_home}}/conf/tomcat-users.xml"
    owner: "{{ tomcat_server_user }}"
    group: "{{ tomcat_server_group }}"
    mode: "640"
  notify: restart tomcat

- name: start tomcat
  service:
    name: "{{tomcat_service_name}}"
    state: started
    enabled: yes
  become: yes
