---

- name: install tomcat
  apt:
    name: "{{ item }}"
    state: present
    cache_valid_time: 3600
  with_items: "{{ tomcat_packages }}"

- name: install tomcat admin
  apt:
    name: "{{ item }}"
    state: present
    cache_valid_time: 3600
  with_items: "{{ tomcat_admin_packages }}"
  when: tomcat_admin_install

- name: start tomcat
  service:
    name: tomcat
    state: started
