---

- name: Add Tomcat User Group
  group:
    name: "{{ tomcat_server_group }}"
  become: yes


- name: Add Tomcat User
  user:
    name: "{{ tomcat_server_user }}"
    group: "{{ tomcat_server_group }}"
    home: "{{ tomcat_user_home }}"
    createhome: no
  become: yes

- name: Download and Extract Tomcat Binary
  unarchive:
    src: "{{ tomcat_binary_url }}"
    dest: "/opt/"
    remote_src: yes
  become: yes

- name: Symlink Installation Directory to Tomcat Home
  file:
    src: "{{ tomcat_target_dir }}"
    path: "{{ tomcat_home }}"
    state: link
  become: yes

- name: Change ownership of target installation directory to Tomcat User and Group
  file:
    path: "{{ tomcat_target_dir }}"
    owner: "{{ tomcat_server_user }}"
    group: "{{ tomcat_server_group }}"
    state: directory
    recurse: yes
  become: yes

- name: Setup Tomcat Systemd Service
  template:
    src: tomcat.service.j2
    dest: /etc/systemd/system/tomcat.service
  notify: restart tomcat
  become: yes
