---

- include: "define-home.yml"
  tags:
    - tomcat
    - tomcat-config
    - tomcat-install

- include: "install-{{ ansible_os_family }}.yml"
  tags:
    - tomcat
    - tomcat-install

- include: config.yml
  static: no
  tags:
    - tomcat
    - tomcat-config
